# Generated by Django 3.2.8 on 2021-11-21 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20211121_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid',
            new_name='new_bid',
        ),
    ]
